package com.nequi.franchises.application.mapper;

import com.nequi.franchises.application.dto.BranchDto;
import com.nequi.franchises.application.dto.CreateBranchRequest;
import com.nequi.franchises.domain.model.Branch;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;

/**
 * Mapper for Branch entities and DTOs.
 * 
 * DESIGN: Branches are embedded in Franchise documents in MongoDB.
 * The BranchDto does NOT contain franchiseId as it's implicit from the parent context.
 */
@Component
public class BranchMapper {

    public Branch toEntity(CreateBranchRequest request) {
        // Note: Branch ID is generated by service, not here
        return Branch.builder()
                .name(request.getName())
                .build();
    }

    public BranchDto toDto(Branch branch) {
        return BranchDto.builder()
                .id(branch.getId())
                .name(branch.getName())
                .createdAt(branch.getCreatedAt())
                .updatedAt(branch.getUpdatedAt())
                .build();
    }

    public Flux<BranchDto> toDtoFlux(Flux<Branch> branches) {
        return branches.map(this::toDto);
    }
}
